[[LFortran]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0315c81728aefdddf8acdc79aa95fbed16e977b8"
libc = "glibc"
os = "linux"

    [[LFortran.download]]
    sha256 = "e19b33135207ff5e68a5995235310778ec955797c26ab56db52de2ebf4aac2c0"
    url = "https://github.com/JuliaBinaryWrappers/LFortran_jll.jl/releases/download/LFortran-v0.18.0+0/LFortran.v0.18.0.x86_64-linux-gnu-cxx11.tar.gz"
[[LFortran]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "498976d4746044b147d4ede1ed68d65609ec8fa6"
libc = "musl"
os = "linux"

    [[LFortran.download]]
    sha256 = "e66f82ca105c5fc99f527129759c8ea261c09bb37d42383df77e6cef6ece348c"
    url = "https://github.com/JuliaBinaryWrappers/LFortran_jll.jl/releases/download/LFortran-v0.18.0+0/LFortran.v0.18.0.x86_64-linux-musl-cxx11.tar.gz"
