# Autogenerated wrapper script for LFortran_jll for x86_64-linux-gnu-cxx11
export cpptranslate, lfortran, liblfortran_runtime

using XML2_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("LFortran")
JLLWrappers.@declare_library_product(liblfortran_runtime, "liblfortran_runtime.so")
JLLWrappers.@declare_executable_product(cpptranslate)
JLLWrappers.@declare_executable_product(lfortran)
function __init__()
    JLLWrappers.@generate_init_header(XML2_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        liblfortran_runtime,
        "share/lfortran/lib/liblfortran_runtime.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        cpptranslate,
        "bin/cpptranslate",
    )

    JLLWrappers.@init_executable_product(
        lfortran,
        "bin/lfortran",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
